############## Controller Parameters ##############
P_pos_XY: 0.95
P_pos_Z: 0.95

P_vel_XY: 1.4
I_vel_XY: 0.4
D_vel_XY: 0.2

P_vel_Z: 4.0
I_vel_Z: 2.0
D_vel_Z: 0.0

max_vel_XY: 12.0
max_vel_Z_DOWN: 1.0
max_vel_Z_UP: 3.0

T_s: 20 # sampling time [milliseconds]

############## Logging Parameters ##############

T_log: 0 # logging start time [seconds]

############## Quadcopter Parameters ##############
g: 9.81                     #gravitational acceleration [m_s2]
quadcopter_mass: 1.5        # Quadcopter mass [kg]
max_motor_thrust: 8.9764    # maximal thrust of one motor [N]
quad_rotor_radius: 0.12     # Quadcopter rotor radius [m]
quad_rotor_distance: 0.35   # Quadcopter rotor distance [m]
sanchez_constant: 2.0       # constant defined in the sanchez publication
rho_air: 1.205              # density of air [kg_m^3]