SIM: true #simulation or real world
P_pos: 1
P_vel: 0.1
I_vel: 1000
D_vel: 0.0035
sample_time: 10 #milliseconds
hover: 0.4
k_h: 0.05
T: 30

#trajectory parameters
v: 0.6
h_0: 2.0
freq: 0.125
amp: 0.75