P_pos_XY: 0.95
P_pos_Z: 0.95

P_vel_XY: 1.4
I_vel_XY: 0.4
D_vel_XY: 0.2

P_vel_Z: 4.0
I_vel_Z: 2.0
D_vel_Z: 0.0

T_s: 20 # sampling time [milliseconds]
T_log: 0 # logging start time [seconds]

#reference generation
circle_frequency: 0.1
