SIM: false #simulation or real world

P_pos_XY: 0.95
P_pos_Z: 0.95

P_vel_XY: 1.4
I_vel_XY: 0.4
D_vel_XY: 0.2

P_vel_Z: 4.0
I_vel_Z: 2.0
D_vel_Z: 0.0

T_s: 20 #milliseconds


#old parameters
v: 0.0
h_0: 1.1
freq: 0.2
amp: 100
hover: 0.4
k_h: 0.05
T: 40
